### ISSUE TITLE
Problem in building the tests

### ISSUE THREAD

**Issue by henshs** [wokast/RePrimAnd#32] opened 2023-05-21 04:56 UTC
I have successfully built and installed RePrimAnd from the source on my Mac m2 Ventura. I tried then to build the tests as described in the 'Unit tests' subsection under 'Running Tests' section in the documentation [https://wokast.github.io/RePrimAnd/installing.html](https://wokast.github.io/RePrimAnd/installing.html), in particular it was build by running the command,

```meson configure -Dbuild_tests=true```.

After that some options appeared in the terminal but I could not find what option to choose and how. I entered "q" to quit and then tried running ```ninja test``` which gives an error

"ninja: error: loading 'build.ninja': No such file or directory".

I would be glad if this issue could be resolved.

**Comment by wokast** [comment] 2023-05-23 09:48
What does some option appear in the terminal mean? Please provide details. Also provide the chain of commands used to get to the above problems. You are probably in the wrong directory when issuing one of these commands.

**Comment by wokast** [comment] 2023-05-23 09:53
It would be good to start with a fresh checkout to debug this. Please provide the output of the commands below (adding any additional options you found necessary to build the library before).

```
cd <repository>
meson mbuild.tst --buildtype=release -Dbuild_tests=true --prefix=<custom install location>
cd mbuild.tst
ninja
ninja test
```

**Comment by henshs** [comment] 2023-05-29 06:32
> What does some option appear in the terminal mean? Please provide details. Also provide the chain of commands used to get to the above problems. You are probably in the wrong directory when issuing one of these commands.

The chain of commands that are used to get to the above problems in what follows. The following commands help to build and install the library:

```cd <repository>```
```conda activate <environment>``` (to activate Conda environment)
```export BOOST_ROOT=/opt/homebrew/opt/boost/include/``` (workaround for Mac)
```meson mbuild --buildtype=release```
```cd mbuild```
```ninja```
```ninja install```

To install the Python interface the following commands are used:

```conda install numpy``` (as I am using Conda environment, so installed ```numpy``` in Conda environment)
```conda install pybind11``` (as I am using Conda environment, so installed ```pybind11``` in Conda environment)
```cd bindings/python```
```CXXFLAGS=-std=c++11 CFLAGS=-std=c++11 CPPFLAGS=-I/opt/homebrew/opt/boost/include/ pip install .``` (workaround for Mac)

I tried then to build the tests as described in the 'Unit tests' subsection under 'Running Tests' section in the documentation [https://wokast.github.io/RePrimAnd/installing.html](https://wokast.github.io/RePrimAnd/installing.html) in particular it was build by running the command,

```meson configure -Dbuild_tests=true```

After that some options appeared in the terminal as it is attached herewith in the ```output.txt``` file. I entered "q" to quit and then tried running 

```ninja test```

 which gives an error in the terminal

```ninja: error: loading 'build.ninja': No such file or directory```.


[output.txt](https://github.com/wokast/RePrimAnd/files/11588769/output.txt)

**Comment by henshs** [comment] 2023-05-29 06:53
> It would be good to start with a fresh checkout to debug this. Please provide the output of the commands below (adding any additional options you found necessary to build the library before).
> 
> ```
> cd <repository>
> meson mbuild.tst --buildtype=release -Dbuild_tests=true --prefix=<custom install location>
> cd mbuild.tst
> ninja
> ninja test
> ```

I tried the following commands as suggested:

```cd <repository>```
```export BOOST_ROOT=/opt/homebrew/opt/boost/include/```  (workaround for Mac)
```meson mbuild.tst --buildtype=release -Dbuild_tests=true```
```cd mbuild.tst```
```ninja```
```ninja test```

While the build is okay, but I see the error after running ```ninja test``` :

```[0/1] Running all tests.```
```No tests defined.```. 

I have attached "meson-log.txt" herewith.

[meson-log.txt](https://github.com/wokast/RePrimAnd/files/11596584/meson-log.txt)

**Comment by wokast** [comment] 2023-05-30 09:33
So far, the problem does not seem to have anything to do with RePrimAnd but like the typical generic problems encountered when building code from source.

Regarding your first try, output.txt starts with 

```
WARNING: The source directory instead of the build directory was specified.
WARNING: Only the default values for the project are printed, and all command line parameters are ignored.
```

This happens you use meson configure without specifying the build directory (mbuild or whatever) unless the current directory is the build directory. I still don't understand what was the interactive question you answered by pressing q. However, the point is moot if meson configure was called without specifying the build folder. 

Regarding the second try, meson-log.txt contains the line
`Build Options: -Dbuildtype=release`
This indicates you did not specify `-Dbuild_tests=true`. It could also be that you are re-using an existing build folder and experience some interference.

**Comment by henshs** [comment] 2023-05-31 03:39
> Regarding your first try, output.txt starts with
> 
> ```
> WARNING: The source directory instead of the build directory was specified.
> WARNING: Only the default values for the project are printed, and all command line parameters are ignored.
> ```
> 
> This happens you use meson configure without specifying the build directory (mbuild or whatever) unless the current directory is the build directory. I still don't understand what was the interactive question you answered by pressing q. However, the point is moot if meson configure was called without specifying the build folder.

Indeed I did not specify the build directory for my first try. There was no interactive questions, my bad.

> Regarding the second try, meson-log.txt contains the line `Build Options: -Dbuildtype=release` This indicates you did not specify `-Dbuild_tests=true`. It could also be that you are re-using an existing build folder and experience some interference.

It's not because of the interference but because of the point exactly as you mentioned that I did not specify `-Dbuild_tests=true`. 

To understand the issue, I have uninstalled everything and installed again the library and python binding. I have found that the problem is related to finding boost library when `-Dbuild_tests=true` option is specified during build. So it is clear that `export BOOST_ROOT=/opt/homebrew/opt/boost/include` does not work when `-Dbuild_tests=true` option is specified. I have attached the "meson-log.txt" which generated during building with the following commands:

`cd <repository>`
`export BOOST_ROOT=/opt/homebrew/opt/boost/include/` (workaround for Mac)
`meson mbuild.tst --buildtype=release -Dbuild_tests=true`


[meson-log.txt](https://github.com/wokast/RePrimAnd/files/11608380/meson-log.txt)

**Comment by wokast** [comment] 2023-05-31 10:11
I just notice that you provide the boost include directory instead of the boost root directory
`BOOST_ROOT=/opt/homebrew/opt/boost/include`. It should be just `BOOST_ROOT=/opt/homebrew/opt/boost`. The reason this only prevents the tests is that the tests are the only component that require a boost library (the unit test library) while the reprimand library itself is only using boost header files. Apparently the meson build system looked for boost library files only in `BOOST_ROOT/lib` but for header files both in `BOOST_ROOT/include` and `BOOST_ROOT`.

**Comment by wokast** [comment] 2023-06-01 10:35
Closing this since it was not a bug after all.

**Closed as completed by wokast** 2023-06-01 10:35 UTC
