### ISSUE TITLE
Build errors in version 1.3

### ISSUE THREAD

**Issue by eschnett** [wokast/RePrimAnd#3] opened 2021-08-10 03:04 UTC
When I build version 1.3, I receive several errors similar to
```
     58    ../tests/benchmarks/src/accuracy_con2prim_mhd.cc: In function 'std::array<double, 9> get_accuracy(EOS_Toolkit::real_t, E
           OS_Toolkit::real_t, EOS_Toolkit::real_t, EOS_Toolkit::eos_thermal, EOS_Toolkit::prim_vars_mhd&, EOS_Toolkit::prim_vars_m
           hd&, EOS_Toolkit::real_t)':
  >> 59    ../tests/benchmarks/src/accuracy_con2prim_mhd.cc:82:10: error: 'numeric_limits' is not a member of 'std'
     60       82 |     std::numeric_limits<real_t>::epsilon()
     61          |          ^~~~~~~~~~~~~~
```

I find that this patch removes these errors:
```patch
--- a/library/EOS_Barotropic/eos_barotr_poly.cc
+++ b/library/EOS_Barotropic/eos_barotr_poly.cc
@@ -1,6 +1,7 @@
 #include "eos_barotr_poly.h"
 #include "eos_barotr_poly_impl.h"
 #include <cmath>
+#include <limits>
 #include <stdexcept>
 
 using namespace std;
--- a/library/EOS_Barotropic/eos_barotr_pwpoly.cc
+++ b/library/EOS_Barotropic/eos_barotr_pwpoly.cc
@@ -1,6 +1,7 @@
 #include "eos_barotr_pwpoly.h"
 #include "eos_barotr_pwpoly_impl.h"
-#include <stdexcept>
-#include <cmath>
+#include <cmath>
+#include <limits>
+#include <stdexcept>
 
 using namespace std;
--- a/tests/benchmarks/src/accuracy_con2prim_mhd.cc
+++ b/tests/benchmarks/src/accuracy_con2prim_mhd.cc
@@ -9,6 +9,7 @@
 #include <fstream>
 #include <iomanip>
 #include <string>
+#include <limits>
 #include "con2prim_imhd.h"
 #include "eos_thermal_file.h"
 #include "eos_hybrid.h"
```

**Comment by wokast** [comment] 2021-08-10 09:08
Thanks for reporting. This is indeed a bug of classic type where missing system headers were not noticed because many compilers include them in other headers. 
For future tests of this: which compiler/OS is reproducing the problem?

**Comment by wokast** [comment] 2021-08-10 10:18
Should be fixed with latest commit 444dee7a82965a4ee0d2e7fab65ff4def9fdff2d
Could you confirm it is now building on your environment?

**Comment by wokast** [comment] 2021-08-10 10:21
Note: the archive contained in the ET thorn was not updated yet, waiting a bit to collect similar problems.

**Comment by eschnett** [comment] 2021-08-10 12:44
Yes, the current `public` branch works fine.

**Comment by wokast** [comment] 2021-09-04 12:34
Updated the archive in the ET thorn as well in commit 1582722ca872643db2fe0413331f78c6396929f9
Both regular build and building within ET thorn should work out of the box now. Closing for now.

**Closed as completed by wokast** 2021-09-04 12:34 UTC
Labels: bug
